### ISSUE TITLE
关于定位板

### ISSUE THREAD

**Issue by cc0h** [fangxx3863/SDVX-CON#1]
大佬你的定位板是在哪里打样的啊？那个定位板的压缩包嘉立创打不开，直接用下单助手的话预览里又没看到相应的开孔，而且也不给免费打样，能请大佬指点一下吗

**Comment by fangxx3863** [comment]
你会在整个工程文件里，看到一个叫PostionBoard的PCB（

**Comment by cc0h** [comment]
感谢，这就去看看
